version: 2
updates:
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Taipei"
    open-pull-requests-limit: 30
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    groups:
      dependencies:
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "flutter_rust_bridge"

  - package-ecosystem: "cargo"
    directory: "/rust"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Taipei"
    open-pull-requests-limit: 30
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    groups:
      dependencies:
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "flutter_rust_bridge"
