// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Session`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`

Stream<CapturedRequest> startCapture() =>
    RustLib.instance.api.crateApiCaptureStartCapture();

Future<void> stopCapture() => RustLib.instance.api.crateApiCaptureStopCapture();

Future<bool> cleanupStaleProxy() =>
    RustLib.instance.api.crateApiCaptureCleanupStaleProxy();

class CapturedRequest {
  final String method;
  final String url;
  final String host;
  final PlatformInt64 timestampMs;
  final String configListUrl;

  const CapturedRequest({
    required this.method,
    required this.url,
    required this.host,
    required this.timestampMs,
    required this.configListUrl,
  });

  @override
  int get hashCode =>
      method.hashCode ^
      url.hashCode ^
      host.hashCode ^
      timestampMs.hashCode ^
      configListUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CapturedRequest &&
          runtimeType == other.runtimeType &&
          method == other.method &&
          url == other.url &&
          host == other.host &&
          timestampMs == other.timestampMs &&
          configListUrl == other.configListUrl;
}
