// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `finish`, `init_tracing_once`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ForwardLayer`, `MessageVisitor`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `on_event`, `record_debug`, `record_str`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `default`

/// Dart 端在 `main()` 內呼叫一次。重複呼叫只會覆蓋現有 sink(idempotent)。
Stream<LogEvent> startLogStream() =>
    RustLib.instance.api.crateApiLoggingStartLogStream();

/// 跨橋傳給 Dart 的 log event。對應 Dart 的 `Logger('rust.<target>').log(level, message, ...)`。
class LogEvent {
  final PlatformInt64 timestampMs;

  /// "ERROR" | "WARN" | "INFO" | "DEBUG" | "TRACE"
  final String level;

  /// tracing target,例如 "mitm" / "ca" / "cert_store" / "panic"
  final String target;
  final String message;

  const LogEvent({
    required this.timestampMs,
    required this.level,
    required this.target,
    required this.message,
  });

  @override
  int get hashCode =>
      timestampMs.hashCode ^
      level.hashCode ^
      target.hashCode ^
      message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LogEvent &&
          runtimeType == other.runtimeType &&
          timestampMs == other.timestampMs &&
          level == other.level &&
          target == other.target &&
          message == other.message;
}
